### ISSUE TITLE
Missing Sources

### ISSUE THREAD

**Issue by Chandler-Kluser** [MiSTeX-devel/MiSTeX-buildroot#2]
The source code of [uboot](http://sources.buildroot.net/uboot/uboot-origin_master-br1.tar.gz) is missing (404 Error), there is any alternative to that?

Also, there are some sources pointing to Gitee Nezha D1 repositories, which are VERY SLOW, do you know if are there any faster mirrors around?

Thanks in advance!

**Comment by hansfbaier** [comment]
What sources are missing exactly? I think everything necessary is here.

**Comment by Chandler-Kluser** [comment]
I miss click the confirm button so the issue was not posted

**Comment by Chandler-Kluser** [comment]
My solution is to replace by [source](http://sources.buildroot.net/uboot/u-boot-2022.04.tar.bz2) in Makefile.

I also would like to take this opportunity and let you know that I have made a [PR](https://github.com/MiSTeX-devel/Arcade-QBert_MiSTeX/pull/1) in [Arcade-QBert](https://github.com/MiSTeX-devel/Arcade-QBert_MiSTeX) MiSTeX repo

**Comment by Chandler-Kluser** [comment]
I also would like to thank you very much for your effort to make this such nice project!!

I was able to fully build the following cores in Vivado 2023.1 for xc7a110t:

- Menu_MiSTeX.bit
- Arcade_QBert_MiSTeX.bit (doing that [PR](https://github.com/MiSTeX-devel/Arcade-QBert_MiSTeX/pull/1) I mentioned)
- FlappyBird_MiSTeX.bit
- Arcade_BombJack_MiSTeX.bit
- Arcade_Pong_MiSTeX.bit; and
- Arcade_Pacman_MiSTeX.bit

I am now trying to build the image to flash my Allwinner D1 board to test in my FPGA

**Comment by hansfbaier** [comment]
Unfortunately, I couldn't get BombJack and Pacman make to work on Artix7 yet.
Probably issues with block ram porting.
Pacman sound still seems to work somewhat if I remember correctly.

**Comment by Chandler-Kluser** [comment]
I have got it to work!

https://github.com/MiSTeX-devel/MiSTeX-buildroot/assets/29960960/fd35574b-66a1-468a-b8b1-5e0452edb086

There are some points to highlight:

- Great input lag from controller (I believe in your videos you did not face this issue)
- I could not play any core, Flappybird at least I could watch a bird flying on the screen :)
- When I ran other cores the screen (and OSD) became in a very weird pink mode:

![image](https://github.com/MiSTeX-devel/MiSTeX-buildroot/assets/29960960/df69578b-a6e7-46d2-aa40-022900bb23b5)


I would like to offer some help, if there is something I can do I will be glad to improve something.

**Comment by hansfbaier** [comment]
Great! The lag affects only the menu, not the games, interestingly.
Of course there is lots to improve. Finding out where that lag comes from, for example.
The bit/byte order of the VGA signal of the other cores is probably wrong, so the colors are off.
BTW. The video you attached above seems to have no image, only audio.
Would be interesting to know the details of 'could not play', you mean the core does not react to the controller.?
If you like we could make a video conference and to try and solve some issues, or I could explain some things and show you around.

**Comment by Chandler-Kluser** [comment]
of course, what is the best of to make contact?

**Comment by hansfbaier** [comment]
Google Meet or zoom would be fine.

**Comment by Chandler-Kluser** [comment]
great!!

I believe I am able to do it tomorrow, I live in Brazil so we can discuss a better time for both of us.

We need a contact to share the meet link

Besides, the video is coded in h265 to fit the 10MB limit of GitHub, it can only be played with an appropriate codec, not in browser.

you could hear the audio because it has been kept in aac format.

**Comment by hansfbaier** [comment]
my email address is hansfbaier@gmail.com

**Comment by hansfbaier** [comment]
Ah I downloaded the video and can see it with vlc now. Is your gamepad USB or bluetooth?

**Comment by Chandler-Kluser** [comment]
USB Gamepad, I was using an 8bitdo BT receiver which acts like a normal USB Xinput gamepad HID device for the USB Host, so it does not matter.

I prefer that way in order not to power consume the regulators with lights and rumble motors from the gamepad (which work through batteries).

I have sent you an email ☺

**Comment by hansfbaier** [comment]
I think we can close this now.
Please reopen, if you think otherwise, and explain why.
