### ISSUE TITLE
Update Build Instructions

### ISSUE THREAD

**Issue by siffland** [MiSTeX-devel/MiSTeX-buildroot#4]
I was playing with this over the weekend and from a vanilla installation of Ubuntu 22.04 the following steps are required for a successful build and thought maybe the instructions could be updated.  I have never done a pull request on github and was not sure if they are being accepted at this time.

```
sudo apt-get install -y git make build-essential file wget cpio unzip rsync bc dosfstools
git clone https://github.com/MiSTeX-devel/MiSTeX-buildroot.git
cd MiSTeX-buildroot
git submodule init
git submodule update
cd rpi-zero
./build.sh 
```
Also about 18GB was required for the build.

Thanks for all the hard work.

**Comment by hansfbaier** [comment]
OK, done. Many thanks!
